import "./globals.css";
import { Inter } from "next/font/google";
import { dir } from "i18next";
import { languages } from "../i18n/settings";

export async function generateStaticParams() {
  return languages.map((lang) => ({ lang }));
}

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { lang } }) {
  return (
    <html lang={lang} dir={dir(lang)}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
